#!/bin/bash
#SBATCH --job-name=Download_gnomad_chr16 # job name (shows up in the queue)
#SBATCH --time=24:00:00 #Walltime (HH:MM:SS)
#SBATCH --mem=1000 # Memory in MB
#SBATCH --cpus-per-task=1

# Setting wd
set -e
cd /home/STUDENT/harjo391/JRA/data/gnomad_chr16
wget https://storage.googleapis.com/gnomad-public/release/2.1.1/liftover_grch38/vcf/genomes/gnomad.genomes.r2.1.1.sites.16.liftover_grch38.vcf.bgz
